### ISSUE TITLE
pc_profile

### ISSUE THREAD

**Issue by melisadr** [ibarraespinosa/vein#33]
I was wondering why the emissions profile does not add 24 * 7 = 168.
I always thought that the sum of the emissions of all hours of the day of the week should add up to the total emissions for that week with a uniform profile.
Thanks in advance,
Mel

**Comment by ibarraespinosa** [comment]
Hi @melisadr 
You are right in all what you said, except in the part where emissions have a uniform profile, which is not true. Hourly emissions vary in space and by type of vehicle. It is very dynamic.

I'm not understanding clearly your question, but I'm gonna add this:

VEIN works with hourly traffic data (see https://www.geosci-model-dev-discuss.net/gmd-2017-193/), this data can be a solely morning rush hourly traffic data, or traffic data different for every hour as a list of traffic data, each element of the list is an hour.

The first case, with morning rush hour, is perhaps the most common. VEIN includes a data of a normalized profile of 24 hours and 7 days of the week. 

```
library(vein)
data(pc_profile)
head(pc_profile)

```
You can use this profile inside the function `emis` to extrapolate morning rush traffic data and estimate emissions, at the same time:

type this:
`?emis`

This is important: This profile represents only Light-Duty Vehicles and different type of vehicles have a different profile. The profiles also change inside the area of study. The best is to have different traffic data at every road, hour of the week for different type of vehicles

**Comment by melisadr** [comment]
Hola Sergio, vi que eres Chileno asi que para una mejor expresión personal
escribire en español.
Entiendo que las emisiones no son uniformes y por eso, buscando una posible
bimodal para probar con el inventario local, encontre esta libreria e
investigue cual era el perfil de emisiones que utilizaban. Estuve viendo el
pc_profile antes de escribirte y note que la suma de todos los pesos daba
alrededor de 100, en lugar de 24*7 como esperaba que diera.  Yo tengo las
emisiones del inventario local en Gg/año y en la busqueda de mejorar la
desagregacion me tope con tu ciclo. Si yo uso tu ciclo tal cual está, la
suma de las emisiones de una semana no me va a dar como el valor de una
semana promedio y a eso me referia con "uniforme" y entiendo que si eso
ocurre, la suma de las emisiones hora por hora nunca me van a permitir
reconstruir el total anual y eso es lo que no entendía y sigo sin entender
sinceramente.
Entiendo que lo mejor sería tener distintos ciclos de emisiones para cada
categoría de vehículo pero no cuento con datos locales, menos podré tener
datos locales con ese nivel de detalle.
Espero que se entienda ahora mi consulta,
Saludos,
Melisa

Melisa Diaz Resquin

**Comment by ibarraespinosa** [comment]
Entendi, 

Tu tienes los totales por año y necesitas desagregar los datos temporalmente. En el caso espacial, tu tienes los datos distribuidos espacialmente tambien? (voy a construir una funcion que desagrega espacialmente inventarios top-down en grades de espaciamiento variable).

El perfil `pc_profile` genera la extrapolación temporal de datos de tráfico de horario punta de mañana. Estos datos estan noramlizados para el horario punta por tanto la suma de ellos no es porcentaje. Tu podrías usar este dato para distribuir temporalmente tus emisiones, pero tienes que considerar que probablemente producirá picos  sobre estimados y tiene sque calcular el porcentaje horario.

Te recomiendo hacer esto:

- Agarra tus emisiones anuales y divide por 52 para para tener las emisiones por semana.
- Calcula el porcentaje horario de los datos `pc_profile`
- Calcula las emisiones horarios con los datos calculados.

Voy a pensar si dejo este issue #33 abierto para crear esta funcion que calcula la distribución espacial de inventarios anuales

**Comment by ibarraespinosa** [comment]
Puedo cerrar esto, cierto?

**Comment by ibarraespinosa** [comment]
@melisadr Voy a re abrir este issue por que voy a crear la funcion que hace esto. Le va a servir a tambien a @Schuch666

**Comment by ibarraespinosa** [comment]
Esta nueva funcion tiene que:

1. Leer emisiones en polygonos espaciales.
2. Leer elementos espaciales para distribuir las emisiones en grillas. Por ahora tienen que ser o distribution de calles o luces nocturnas. El usuario debe poder escoger.
3. Leer la grila.
4. Leer perfil temporal para producir emisiones horarias.
5. Retorna una grilla de emisiones.

Esta funcion sería parecida a emis_grid que produce una interseccion entre calles (lineas) y polygonos. 
La diferencia es que si se usa luces leeria un raster o una matriz. 
Si se usan calles, podria usarse una grilla de polygonos de una intersección entre calles y grilla, esto lo haría emis_grid, el campo a interseccionar seria la longitud de calles. Ahora, cuales calles?  Considerando solo motorways sería bueno para camiones. Considerando calles mas urbanas como primary sería mejor representar emisiones de CO y HC. Para representar el CO2 podrian ser en todas las calles. Esto quedaría a criterio del usuario. En ese caso, el vector de lineas deberia tener longitud de calle para cada tipo de calle.

En resumen, sería una funcion que multiplicaría una grilla ponderadas y normalizada (100%) con polygonos con emisiones y perfiles. Deberia ser una vez por contaminante, proablemente con la opcion de una lista de contaminante y grillas y un factor multiplicador k.

emis_grid_topdown <- function(emis_polygon, g_ponderada, perfil,  k){
# interseccion polygon g_ponderada
...
}

**Comment by ibarraespinosa** [comment]
@melisadr  las functiones streetDist y  territory de **EmissV** producen espacialización de emisiones con perfiles. Mira https://github.com/Schuch666/EmissV/blob/master/R/streetDist.R 

Saludos

Cerradno este issue

**Comment by Schuch666** [comment]
Ola

The [EmissV](https://github.com/Schuch666/EmissV) function names has changed to a better presentation: territory become 'areaSource' and generates a raster with can be used as a spatial distribution of pollutants with 'rasterSousce' or merged with other areaSources with 'emission' to generate spatial distribution of pollutants

Some specialized functions to expand hourly the emissions and to set the weekday/hour are present in the [eixport](https://github.com/ibarraespinosa/eixport) package

@melisadr you can use something like 'pc_profile = pc_profile / sum(pc_profile)' or 'pc_profile[,i] = pc_profile[,i] / sum(pc_profile[,i])' to conserve mass if you need
